# Generated by Django 2.2 on 2020-12-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopost',
            name='id',
        ),
        migrations.AlterField(
            model_name='infopost',
            name='index',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
