# Generated by Django 2.2 on 2020-11-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20201118_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total price'),
        ),
    ]
