# Generated by Django 2.2 on 2020-11-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201117_0742'),
        ('cart', '0008_auto_20201121_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, blank=True, to='product.Product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
