# Generated by Django 2.2 on 2020-11-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201117_0742'),
        ('cart', '0011_auto_20201123_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, blank=True, to='product.Product', verbose_name='Product'),
        ),
    ]
