# Generated by Django 2.2 on 2020-12-27 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0009_auto_20201204_1857')
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_timedate', models.DateTimeField(default=datetime.datetime.now)),
                ('orders_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipment_type', models.CharField(choices=[('Courier_delivery', 'Courier delivery'), ('Mail_delivery', 'Mail delivery'), ('Pickup', 'Pickup')], default='Pickup', max_length=20)),
                ('status', models.CharField(choices=[('Processed', 'Processed'), ('On_the_road', 'On the road'), ('Ready_for_delivery', 'Ready for delivery'), ('Received_by_the_customer', 'Received by the customer')], default='Processed', max_length=20)),
                ('is_it_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('content', models.ManyToManyField(to='product.Product')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile')),
            ],
        ),
    ]
