# Generated by Django 2.2.12 on 2020-11-22 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Корзина')),
                ('code', models.CharField(blank=True, db_index=True, default=None, max_length=20, null=True, verbose_name='Промо код')),
                ('valid_date_start', models.DateTimeField(auto_now_add=True, verbose_name='Начало действия')),
                ('valid_date_end', models.DateTimeField(default=datetime.datetime(2021, 2, 20, 16, 56, 1, 559024, tzinfo=utc), verbose_name='Конец действия')),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Номинал скидки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
    ]
