# Generated by Django 2.2 on 2020-12-07 08:47

import datetime
import discount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=discount.models.compute_default_to, verbose_name='Active to'),
        ),
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Active from'),
        ),
    ]
