# Generated by Django 2.2 on 2020-11-28 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 18, 12, 16, 8832, tzinfo=utc), verbose_name='Active to'),
        ),
    ]
