# Generated by Django 2.2 on 2020-11-28 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20201128_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 20, 54, 44, 880090, tzinfo=utc), verbose_name='Active to'),
        ),
    ]
