# Generated by Django 2.2 on 2020-12-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20201212_2014'),
        ('discount', '0002_auto_20201207_1047'),
    ]

    operations = [
    ]
