# Generated by Django 2.2 on 2020-12-01 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20201128_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 20, 40, 10, 210352, tzinfo=utc), verbose_name='Active to'),
        ),
    ]
