# Generated by Django 2.2 on 2020-11-26 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20201126_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 15, 23, 17, 386843, tzinfo=utc), verbose_name='Active to'),
        ),
    ]
