# Generated by Django 2.2 on 2020-12-02 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_auto_20201202_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 11, 12, 16, 542453, tzinfo=utc), verbose_name='Active to'),
        ),
    ]
