# Generated by Django 2.2 on 2020-12-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20201207_1047'),
        ('discount', '0007_auto_20201207_2200'),
    ]

    operations = [
    ]
