# Generated by Django 2.2 on 2020-12-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_merge_20201213_1518'),
        ('discount', '0009_auto_20201210_1117'),
    ]

    operations = [
    ]
