# Generated by Django 2.2 on 2020-11-26 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_auto_20201126_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 35, 26, 332103, tzinfo=utc), verbose_name='Active to'),
        ),
    ]
