# Generated by Django 2.2 on 2020-12-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0010_merge_20201215_0955'),
        ('discount', '0004_auto_20201214_2314'),
    ]

    operations = [
    ]
