# Generated by Django 2.2 on 2020-11-26 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0010_auto_20201126_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 20, 30, 52, 851323, tzinfo=utc), verbose_name='Active to'),
        ),
    ]
