# Generated by Django 2.2 on 2020-12-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20201213_1814'),
        ('discount', '0011_merge_20201217_2240'),
        ('discount', '0011_merge_20201217_1204'),
        ('discount', '0002_auto_20201220_1022'),
    ]

    operations = [
    ]
