# Generated by Django 2.2 on 2020-12-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0012_merge_20201220_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Active from'),
        ),
    ]
