# Generated by Django 2.2 on 2020-11-26 20:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0013_auto_20201126_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 20, 42, 56, 197363, tzinfo=utc), verbose_name='Active to'),
        ),
    ]
