# Generated by Django 2.2 on 2020-11-27 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0016_auto_20201127_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 7, 55, 1, 221072, tzinfo=utc), verbose_name='Active to'),
        ),
    ]
