# Generated by Django 2.2 on 2020-11-27 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0022_auto_20201127_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 11, 9, 34, 892537, tzinfo=utc), verbose_name='Active to'),
        ),
    ]
