# Generated by Django 2.2 on 2020-11-27 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0023_auto_20201127_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 16, 41, 39, 148618, tzinfo=utc), verbose_name='Active to'),
        ),
    ]
