# Generated by Django 2.2 on 2020-11-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201116_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='index',
            field=models.IntegerField(),
        ),
    ]
