# Generated by Django 2.2 on 2020-12-13 19:45

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='parent_category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Catalog'),
        ),
    ]
