# Generated by Django 2.2 on 2020-12-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201213_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='level',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='catalog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Catalog'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
