# Generated by Django 2.2 on 2020-12-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20201221_1402'),
        ('catalog', '0011_auto_20201220_1625'),
    ]

    operations = [
    ]
