# Generated by Django 2.2 on 2020-11-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulKarma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.ManyToManyField(to='comments.Reviews')),
            ],
        ),
        migrations.DeleteModel(
            name='UsefulPlusMinas',
        ),
    ]
