# Generated by Django 2.2 on 2020-11-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20201113_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewlike',
            old_name='reviews',
            new_name='review',
        ),
    ]
