# Generated by Django 2.2 on 2020-11-18 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20201113_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='comments.Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='ReviewLike',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='disliked_review',
            field=models.ManyToManyField(blank=True, related_name='disliked_review', to='comments.Review'),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='liked_review',
            field=models.ManyToManyField(blank=True, related_name='liked_review', to='comments.Review'),
        ),
    ]
