# Generated by Django 2.2 on 2020-11-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201117_0742'),
        ('comments', '0005_auto_20201118_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImageReview',
            new_name='ReviewImage',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='rewiew_product'),
        ),
    ]
