# Generated by Django 2.2 on 2020-11-28 20:54

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20201124_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='review_photo',
            field=models.ImageField(blank=True, null=True, upload_to=comments.models.review_photo_path),
        ),
    ]
