# Generated by Django 2.2 on 2020-12-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20201128_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='rating',
            new_name='negative_rating',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='positive_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
