# Generated by Django 2.2 on 2020-11-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20201111_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='verb',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='notification_message', max_length=200),
        ),
    ]
