# Generated by Django 2.2 on 2020-11-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20201113_1207'),
        ('notifications', '0008_auto_20201114_1912'),
    ]

    operations = [
    ]
