# Generated by Django 2.2 on 2020-11-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20201114_1912'),
        ('notifications', '0006_auto_20201116_1150'),
    ]

    operations = [
    ]
