# Generated by Django 2.2 on 2020-11-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20201118_1714'),
        ('notifications', '0010_auto_20201116_1647'),
    ]

    operations = [
    ]
