# Generated by Django 2.2 on 2020-11-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20201116_0756'),
        ('notifications', '0010_auto_20201118_1714'),
        ('notifications', '0010_auto_20201116_1647'),
    ]

    operations = [
    ]
