# Generated by Django 2.2 on 2020-11-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_merge_20201119_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.TextField(default='GASTRONOM info', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_method',
            field=models.CharField(choices=[('email', 'E-mail'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('sms', 'sms'), ('site', 'Site')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source',
            field=models.CharField(choices=[('rest_framework', 'rest_framework'), ('user_profile', 'user_profile'), ('jet', 'jet'), ('comments.apps.CommentsConfig', 'comments.apps.CommentsConfig'), ('notifications', 'notifications'), ('catalog', 'catalog'), ('product.apps.ProductConfig', 'product.apps.ProductConfig'), ('django.contrib.admin', 'django.contrib.admin'), ('django.contrib.auth', 'django.contrib.auth'), ('django.contrib.contenttypes', 'django.contrib.contenttypes'), ('django.contrib.sessions', 'django.contrib.sessions'), ('django.contrib.messages', 'django.contrib.messages'), ('django.contrib.staticfiles', 'django.contrib.staticfiles'), ('cart', 'cart')], max_length=200),
        ),
    ]
