# Generated by Django 2.2 on 2020-11-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_auto_20201128_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramincomemessage',
            name='telegramuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.TelegramUser'),
        ),
    ]
