# Generated by Django 2.2 on 2020-11-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_auto_20201125_1536'),
        ('notifications', '0009_auto_20201116_0756'),
    ]

    operations = [
    ]
