# Generated by Django 2.2 on 2020-11-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_auto_20201121_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Telegram User ID'),
        ),
    ]
