# Generated by Django 2.2 on 2020-11-26 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_user'),
        ('notifications', '0014_telegramreplymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile'),
        ),
    ]
