# Generated by Django 2.2 on 2020-11-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_auto_20201121_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_user_name',
            field=models.TextField(default='', verbose_name='Telegram User Name'),
        ),
    ]
