# Generated by Django 2.2 on 2020-11-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_telegramincomemessage_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramReplyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_message', models.TextField(max_length=500)),
                ('reply_to_message_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.TelegramIncomeMessage')),
            ],
        ),
    ]
