# Generated by Django 2.2 on 2020-11-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_telegramuser_telegram_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='telegram_user',
        ),
    ]
