# Generated by Django 2.2 on 2020-11-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_telegramreplymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramreplymessage',
            name='reply_to_message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.TelegramIncomeMessage'),
        ),
    ]
