# Generated by Django 2.2 on 2020-11-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_telegramuser_telegram_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='telegram_id',
            new_name='chat_id',
        ),
    ]
