# Generated by Django 2.2 on 2020-11-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_telegramuser_telegram_user'),
        ('notifications', '0011_merge_20201124_2133'),
    ]

    operations = [
    ]
