# Generated by Django 2.2 on 2020-11-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_auto_20201127_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_method',
            field=models.CharField(choices=[('email', 'email'), ('telegram', 'telegram'), ('viber', 'viber'), ('sms', 'sms'), ('site', 'site')], default='email', max_length=20),
        ),
    ]
