# Generated by Django 2.2 on 2020-11-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_auto_20201128_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramreplymessage',
            name='reply_to_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.TelegramIncomeMessage'),
        ),
    ]
