# Generated by Django 2.2 on 2020-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_auto_20201128_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramincomemessage',
            name='chat_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
