# Generated by Django 2.2 on 2020-11-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0023_auto_20201128_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramincomemessage',
            name='reply_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.TelegramIncomeMessage'),
        ),
    ]
