# Generated by Django 2.2 on 2020-11-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0024_telegramincomemessage_reply_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramincomemessage',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Text'),
        ),
    ]
