# Generated by Django 2.2 on 2020-11-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0025_auto_20201129_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramincomemessage',
            options={'verbose_name': 'Income message'},
        ),
        migrations.AlterModelOptions(
            name='telegramreplymessage',
            options={'verbose_name': 'Reply message'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'User'},
        ),
        migrations.RemoveField(
            model_name='telegramincomemessage',
            name='reply_message',
        ),
        migrations.AlterField(
            model_name='notification',
            name='source',
            field=models.CharField(choices=[('rest_framework', 'rest_framework'), ('django_filters', 'django_filters'), ('user_profile', 'user_profile'), ('jet', 'jet'), ('comments.apps.CommentsConfig', 'comments.apps.CommentsConfig'), ('notifications', 'notifications'), ('catalog', 'catalog'), ('super_inlines', 'super_inlines'), ('product.apps.ProductConfig', 'product.apps.ProductConfig'), ('django.contrib.admin', 'django.contrib.admin'), ('django.contrib.auth', 'django.contrib.auth'), ('django.contrib.contenttypes', 'django.contrib.contenttypes'), ('django.contrib.sessions', 'django.contrib.sessions'), ('django.contrib.messages', 'django.contrib.messages'), ('django.contrib.staticfiles', 'django.contrib.staticfiles'), ('discount', 'discount'), ('cart', 'cart')], max_length=200),
        ),
    ]
