# Generated by Django 2.2 on 2020-11-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0026_auto_20201130_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram user'},
        ),
    ]
