# Generated by Django 2.2 on 2020-11-30 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0027_auto_20201130_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramincomemessage',
            name='chat_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Chat_id'),
        ),
        migrations.AlterField(
            model_name='telegramincomemessage',
            name='message_id',
            field=models.CharField(max_length=20, verbose_name='Message id'),
        ),
        migrations.AlterField(
            model_name='telegramincomemessage',
            name='telegramuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.TelegramUser', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='telegramincomemessage',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Income message'),
        ),
        migrations.AlterField(
            model_name='telegramreplymessage',
            name='reply_message',
            field=models.TextField(max_length=200, verbose_name='Reply message'),
        ),
        migrations.AlterField(
            model_name='telegramreplymessage',
            name='reply_to_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.TelegramIncomeMessage', verbose_name='Income message'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_user_name',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_user_phone',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='User phone number'),
        ),
    ]
