# Generated by Django 2.2 on 2020-11-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0028_auto_20201130_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
