# Generated by Django 2.2 on 2020-12-01 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0030_auto_20201201_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramincomemessage',
            name='telegramuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.TelegramUser', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='telegramreplymessage',
            name='reply_to_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.TelegramIncomeMessage', verbose_name='Income message'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_phone',
            field=models.TextField(blank=True, max_length=50, null=True, unique=True, verbose_name='User phone number'),
        ),
    ]
