# Generated by Django 2.2 on 2020-12-04 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0031_auto_20201201_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramincomemessage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='telegramincomemessage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
