# Generated by Django 2.2 on 2020-12-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0033_auto_20201204_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_sent',
            new_name='sent',
        ),
    ]
