# Generated by Django 2.2 on 2020-12-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0034_auto_20201205_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
