# Generated by Django 2.2 on 2020-12-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0035_auto_20201205_1353'),
        ('notifications', '0016_auto_20201126_2206'),
    ]

    operations = [
    ]
