# Generated by Django 2.2 on 2020-12-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0035_auto_20201205_1353'),
        ('notifications', '0014_auto_20201202_1251'),
    ]

    operations = [
    ]
