# Generated by Django 2.2 on 2020-12-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0037_auto_20201212_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramincomemessage',
            name='text',
            field=models.TextField(max_length=100, verbose_name='Income message'),
        ),
    ]
