# Generated by Django 2.2 on 2020-12-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0037_auto_20201207_2200'),
        ('notifications', '0038_auto_20201207_1126'),
        ('notifications', '0036_auto_20201209_1438'),
    ]

    operations = [
    ]
