# Generated by Django 2.2 on 2020-12-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0038_auto_20201212_2038'),
        ('notifications', '0038_auto_20201207_1126'),
    ]

    operations = [
    ]
