# Generated by Django 2.2 on 2020-12-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0039_merge_20201213_1518'),
        ('notifications', '0040_auto_20201210_1117'),
    ]

    operations = [
    ]
