# Generated by Django 2.2 on 2020-12-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0041_merge_20201215_0955'),
        ('notifications', '0040_auto_20201214_2314'),
    ]

    operations = [
    ]
