# Generated by Django 2.2 on 2020-12-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0036_auto_20201220_1022'),
        ('notifications', '0041_auto_20201213_2112'),
        ('notifications', '0042_merge_20201217_2240'),
        ('notifications', '0042_merge_20201217_1204'),
    ]

    operations = [
    ]
