# Generated by Django 2.2 on 2020-12-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0044_auto_20201220_1625'),
        ('notifications', '0044_auto_20201221_1324'),
    ]

    operations = [
    ]
