# Generated by Django 2.2 on 2020-12-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0045_merge_20201224_1013'),
        ('notifications', '0045_merge_20201226_1227'),
    ]

    operations = [
    ]
