# Generated by Django 2.2 on 2020-11-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20201118_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[('Male', 'Male'), ('Female', 'Female'), ('not specified', 'not specified')]),
        ),
    ]
