# Generated by Django 2.2 on 2020-11-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20201127_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
