# Generated by Django 2.2 on 2020-11-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20201116_0756'),
        ('user_profile', '0002_auto_20201116_1647'),
        ('user_profile', '0003_auto_20201118_1719'),
    ]

    operations = [
    ]
