# Generated by Django 2.2 on 2020-10-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200326_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_desc',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=100),
        ),
    ]
