# Generated by Django 2.2 on 2020-11-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201116_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descriptions',
            new_name='product_descriptions',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='raiting',
            new_name='product_raiting',
        ),
    ]
