# Generated by Django 2.2 on 2020-11-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201111_1818'),
        ('product', '0003_auto_20201116_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='catalog.Catalog'),
        ),
    ]
