# Generated by Django 2.2 on 2020-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_descriptions',
            field=models.CharField(max_length=1000),
        ),
    ]
