# Generated by Django 2.2 on 2020-11-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201117_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_descriptions',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_raiting',
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='raiting',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='AA22qq55', max_length=10),
        ),
    ]
