# Generated by Django 2.2 on 2020-11-25 10:51

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201122_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', '-price']},
        ),
        migrations.AlterField(
            model_name='media',
            name='product_image',
            field=models.ImageField(default='product.jpg', null=True, upload_to='products/%Y/%m%d'),
        ),
    ]
