# Generated by Django 2.2 on 2020-11-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201125_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'ordering': ['product_id']},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['product_id']},
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
