# Generated by Django 2.2 on 2020-11-25 15:33

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201125_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product_image',
            field=models.ImageField(null=True, upload_to=product.models.Media.generate_upload_path),
        ),
    ]
