# Generated by Django 2.2 on 2020-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20201126_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='large_image',
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(null=True, upload_to='products/%Y/%m/%d/original/'),
        ),
    ]
