# Generated by Django 2.2 on 2020-11-26 20:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201126_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images/%Y%m'),
        ),
    ]
