# Generated by Django 2.2 on 2020-11-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productmedia_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='thumbnail',
        ),
    ]
