# Generated by Django 2.2 on 2020-11-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productmedia_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='thumbnail',
        ),
    ]
