# Generated by Django 2.2 on 2020-11-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_productmedia_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmedia',
            options={},
        ),
    ]
