# Generated by Django 2.2 on 2020-12-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20201207_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmedia',
            old_name='image',
            new_name='original_image',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='product_image',
        ),
        migrations.AddField(
            model_name='productmedia',
            name='thumbnail_image',
            field=models.ImageField(editable=False, null=True, upload_to='products/%Y/%m/%d/thumbnails/'),
        ),
    ]
