# Generated by Django 2.2 on 2021-01-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20201212_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='characteristic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='descriptions',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='original_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/original/'),
        ),
    ]
