# Generated by Django 2.2 on 2021-01-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20210115_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='descriptions',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='original_image',
            field=models.ImageField(null=True, upload_to='products/%Y/%m/%d/original/'),
        ),
    ]
