# Generated by Django 2.2 on 2021-01-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210115_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='productcount',
        ),
    ]
